/**
 * Clipboard Utilities for Chess-Sensei
 *
 * Provides rich clipboard functionality for:
 * - Copying game analysis as formatted HTML
 * - Copying move history with styling
 * - Sharing annotated games
 *
 * Uses Neutralino 6.0.0+ clipboard.writeHTML() API
 * @see https://neutralino.js.org/docs/api/clipboard/
 */

import { clipboard } from '@neutralinojs/lib';
import { frontendLogger } from './frontend-logger';

/**
 * Generate HTML for game analysis
 * Creates a formatted, printable HTML report
 */
function generateAnalysisHTML(gameId: string | null): string {
  const content = document.getElementById('analysis-content');
  if (!content) {
    return '<p>No analysis available</p>';
  }

  // Get all analysis sections
  const sections = Array.from(content.children);

  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Chess-Sensei Analysis Report</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #2c3e50;
      border-bottom: 2px solid #3498db;
      padding-bottom: 10px;
    }
    h2 {
      color: #34495e;
      margin-top: 30px;
    }
    .metadata {
      background: #ecf0f1;
      padding: 15px;
      border-radius: 5px;
      margin-bottom: 20px;
    }
    .move-list {
      font-family: 'Courier New', monospace;
      background: #f8f9fa;
      padding: 15px;
      border-left: 4px solid #3498db;
      margin: 10px 0;
    }
    .mistake {
      background: #ffebee;
      border-left: 4px solid #e74c3c;
      padding: 10px;
      margin: 10px 0;
    }
    .good-move {
      background: #e8f5e9;
      border-left: 4px solid #27ae60;
      padding: 10px;
      margin: 10px 0;
    }
    .evaluation {
      font-weight: bold;
      color: #2980b9;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
    }
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    th {
      background: #34495e;
      color: white;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #bdc3c7;
      color: #7f8c8d;
      font-size: 0.9em;
    }
  </style>
</head>
<body>
  <h1>♟️ Chess-Sensei Analysis Report</h1>
  <div class="metadata">
    <strong>Generated:</strong> ${new Date().toLocaleString()}<br>
    ${gameId ? `<strong>Game ID:</strong> ${gameId}<br>` : ''}
  </div>
`;

  // Add content sections
  sections.forEach((section) => {
    html += section.outerHTML;
  });

  html += `
  <div class="footer">
    <p>Generated by Chess-Sensei v1.0.0</p>
    <p>A modern chess training application with real-time AI-assisted move guidance</p>
  </div>
</body>
</html>`;

  return html;
}

/**
 * Generate HTML for move history
 */
function generateMoveHistoryHTML(): string {
  const moveList = document.getElementById('move-list');
  if (!moveList || !moveList.textContent?.trim()) {
    return '<p>No moves recorded</p>';
  }

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Chess-Sensei Move History</title>
  <style>
    body {
      font-family: 'Courier New', monospace;
      line-height: 1.8;
      color: #2c3e50;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      background: #f8f9fa;
    }
    h1 {
      text-align: center;
      color: #34495e;
    }
    .move-list {
      background: white;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }
    .move-number {
      font-weight: bold;
      color: #7f8c8d;
    }
  </style>
</head>
<body>
  <h1>♟️ Move History</h1>
  <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
  <div class="move-list">
    ${moveList.innerHTML}
  </div>
  <p style="text-align: center; color: #7f8c8d; margin-top: 30px;">
    Chess-Sensei v1.0.0
  </p>
</body>
</html>`;
}

/**
 * Copy analysis report to clipboard as HTML
 */
export async function copyAnalysisAsHTML(): Promise<void> {
  try {
    frontendLogger.info('Clipboard', 'Copying analysis as HTML');

    const analysisOverlay = document.getElementById('analysis-overlay');
    if (!analysisOverlay || analysisOverlay.classList.contains('hidden')) {
      // eslint-disable-next-line no-alert
      alert('No analysis to copy. Please open an analysis first.');
      return;
    }

    // Generate HTML
    const html = generateAnalysisHTML(null);

    // Copy to clipboard
    await clipboard.writeHTML(html);

    frontendLogger.info('Clipboard', 'Analysis copied to clipboard as HTML');
    showCopyNotification('Analysis copied to clipboard!');
  } catch (error) {
    frontendLogger.error('Clipboard', 'Failed to copy analysis:', error);

    // Fallback to plain text copy
    try {
      const analysisText = document.getElementById('analysis-content')?.innerText || '';
      await navigator.clipboard.writeText(analysisText);
      showCopyNotification('Analysis copied as plain text (HTML not supported)');
    } catch (_fallbackError) {
      // eslint-disable-next-line no-alert
      alert('Failed to copy analysis to clipboard.');
    }
  }
}

/**
 * Copy move history to clipboard as HTML
 */
export async function copyMoveHistoryAsHTML(): Promise<void> {
  const moveList = document.getElementById('move-list');
  if (!moveList || !moveList.textContent?.trim()) {
    // eslint-disable-next-line no-alert
    alert('No moves to copy. Play some moves first.');
    return;
  }

  try {
    frontendLogger.info('Clipboard', 'Copying move history as HTML');

    // Generate HTML
    const html = generateMoveHistoryHTML();

    // Copy to clipboard
    await clipboard.writeHTML(html);

    frontendLogger.info('Clipboard', 'Move history copied to clipboard as HTML');
    showCopyNotification('Move history copied to clipboard!');
  } catch (error) {
    frontendLogger.error('Clipboard', 'Failed to copy move history:', error);

    // Fallback to plain text
    try {
      const moveText = moveList.innerText || '';
      await navigator.clipboard.writeText(moveText);
      showCopyNotification('Move history copied as plain text');
    } catch (_fallbackError) {
      // eslint-disable-next-line no-alert
      alert('Failed to copy move history to clipboard.');
    }
  }
}

/**
 * Show a temporary notification that content was copied
 */
function showCopyNotification(message: string): void {
  // Create notification element
  const notification = document.createElement('div');
  notification.className = 'copy-notification';
  notification.textContent = `✓ ${message}`;
  notification.style.cssText = `
    position: fixed;
    top: 20px;
    right: 20px;
    background: #27ae60;
    color: white;
    padding: 15px 20px;
    border-radius: 5px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.2);
    z-index: 10000;
    animation: slideIn 0.3s ease-out;
  `;

  document.body.appendChild(notification);

  // Remove after 3 seconds
  setTimeout(() => {
    notification.style.animation = 'slideOut 0.3s ease-in';
    setTimeout(() => notification.remove(), 300);
  }, 3000);
}

/**
 * Add CSS animations for notifications
 */
if (typeof window !== 'undefined') {
  const style = document.createElement('style');
  style.textContent = `
    @keyframes slideIn {
      from {
        transform: translateX(400px);
        opacity: 0;
      }
      to {
        transform: translateX(0);
        opacity: 1;
      }
    }
    @keyframes slideOut {
      from {
        transform: translateX(0);
        opacity: 1;
      }
      to {
        transform: translateX(400px);
        opacity: 0;
      }
    }
  `;
  document.head.appendChild(style);
}
